import type { Metadata } from "next";
import "./globals.css";
import { ReactNode } from "react";
import { Root } from "@/components/Root";
import { Navigation } from "@/components/navigation";
import { UserProvider } from "@/context/userContext";

export const metadata: Metadata = {
  title: "Дневник снов",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="ru">
      <body>
        <Root>
          <UserProvider>
            <div className="flex flex-col relative">
              <main>{children}</main>
              <div className="fixed w-full bottom-0 left-0">
                <Navigation />
              </div>
            </div>
          </UserProvider>
        </Root>
      </body>
    </html>
  );
}
